[versions]
agpVersion = "8.3.2"
kotlinVersion = "1.9.0"
coreKtxVersion = "1.10.1"
junitVersion = "4.13.2"
espressoVersion = "3.6.1"
lifecycleRuntimeKtxVersion = "2.6.1"
activityComposeVersion = "1.7.0"
composeBomVersion = "2023.08.00"
composeLifeCycleVersion = "2.6.1"
composeCoilVersion = "2.0.0"
hiltVersion = "2.50"
androidxHiltVersion = "1.2.0"
coroutineVersion = "1.9.0"
retroFitVersion = "2.9.0"

[libraries]
#di
daggerHilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hiltVersion" }
kaptHiltCompiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hiltVersion" }

#threading
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutineVersion" }

#androidx core
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtxVersion" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtxVersion" }

#serialization
retrofit-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retroFitVersion" }

#networking
network-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retroFitVersion" }

#compose
compose-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidxHiltVersion" }
compose-coil = { module = "io.coil-kt:coil-compose", version.ref = "composeCoilVersion" }
compose-lifecycle = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "composeLifeCycleVersion" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBomVersion" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "activityComposeVersion" }

#testing
junit = { group = "junit", name = "junit", version.ref = "junitVersion" }
espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoVersion" }

[plugins]
application-plug = { id = "com.android.application", version.ref = "agpVersion" }
kotlin-plug = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinVersion" }
library-plug = { id = "com.android.library", version.ref = "agpVersion" }
hilt-plug = { id = "com.google.dagger.hilt.android", version.ref = "hiltVersion" }